[package]
name = "boatbomber/distortion-screen-rain"
description = "Creates small “water droplets” on screen for immersion"
version = "1.0.2"
license = "MIT"
authors = ["boatbomber (https://boatbomber.com)"]
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json"]
exclude = ["**"]
